TPRUN-3432 Ensure secure Spring version.
Talend/activemq pull request #14
Opened 2022-04-06 13:12 UTC by andreasmattes

2022-04-07 09:18 UTC, jgreffe requested changes

2022-04-07 09:18 UTC, jgreffe commented on activemq-karaf/src/main/resources/features.xml
> -    <feature name="activemq-web-console" version="${upstream.version}">
Beware of this feature removal, if customer installed it before patch, customer won't be able to uninstall anymore.

2022-04-07 10:05 UTC, andreasmattes commented on activemq-karaf/src/main/resources/features.xml
> -    <feature name="activemq-web-console" version="${upstream.version}">
so we should rather add an empty feature I think

2022-04-07 12:44 UTC, andreasmattes commented on activemq-karaf/src/main/resources/features.xml
> -    <feature name="activemq-web-console" version="${upstream.version}">
done

2022-04-08 06:23 UTC, jgreffe approved these changes
Let's hope customers won't use `activemq-web-console` ....

2022-04-08 07:19 UTC, merged